<?xml version="1.0" encoding="utf-8"?><Database Name="VHW2128139" Class="DrugDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-QFSTNQ7\SQLEXPRESS;Initial Catalog=VHW2128139;Integrated Security=True" SettingsObjectName="VHWs.Properties.Settings" SettingsPropertyName="VHW2128139ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Drug" Member="Drugs">
    <Type Name="Drug">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="batch_lot_number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="expiry_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Drug_DeletedRecord" Member="DeletedRecords" ThisKey="ID" OtherKey="drug_id" Type="DeletedRecord" />
    </Type>
  </Table>
  <Table Name="dbo.DeletedRecords" Member="DeletedRecords">
    <Type Name="DeletedRecord">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="drug_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="batch_lot_number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="expiry_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Drug_DeletedRecord" Member="Drug" ThisKey="drug_id" OtherKey="ID" Type="Drug" IsForeignKey="true" />
    </Type>
  </Table>
</Database>